// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/blah/pkg/models/shared"
	"net/http"
)

type PostSendIntegerEnumArrayRequest struct {
	RequestBody []shared.SuiteCode `request:"mediaType=application/json"`
	Array       bool               `queryParam:"style=form,explode=true,name=array"`
}

func (o *PostSendIntegerEnumArrayRequest) GetRequestBody() []shared.SuiteCode {
	if o == nil {
		return []shared.SuiteCode{}
	}
	return o.RequestBody
}

func (o *PostSendIntegerEnumArrayRequest) GetArray() bool {
	if o == nil {
		return false
	}
	return o.Array
}

type PostSendIntegerEnumArrayResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// 500 Global
	GlobalTestException *shared.GlobalTestException
	ServerResponse      *shared.ServerResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostSendIntegerEnumArrayResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostSendIntegerEnumArrayResponse) GetGlobalTestException() *shared.GlobalTestException {
	if o == nil {
		return nil
	}
	return o.GlobalTestException
}

func (o *PostSendIntegerEnumArrayResponse) GetServerResponse() *shared.ServerResponse {
	if o == nil {
		return nil
	}
	return o.ServerResponse
}

func (o *PostSendIntegerEnumArrayResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostSendIntegerEnumArrayResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
