// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/blah/pkg/models/shared"
	"net/http"
)

type SendStringArrayRequestBody struct {
	Strings []string `form:"name=strings"`
}

func (o *SendStringArrayRequestBody) GetStrings() []string {
	if o == nil {
		return []string{}
	}
	return o.Strings
}

type SendStringArrayRequest struct {
	RequestBody *SendStringArrayRequestBody `request:"mediaType=application/x-www-form-urlencoded"`
	Array       bool                        `queryParam:"style=form,explode=true,name=array"`
}

func (o *SendStringArrayRequest) GetRequestBody() *SendStringArrayRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *SendStringArrayRequest) GetArray() bool {
	if o == nil {
		return false
	}
	return o.Array
}

type SendStringArrayResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// 500 Global
	GlobalTestException *shared.GlobalTestException
	ServerResponse      *shared.ServerResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *SendStringArrayResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SendStringArrayResponse) GetGlobalTestException() *shared.GlobalTestException {
	if o == nil {
		return nil
	}
	return o.GlobalTestException
}

func (o *SendStringArrayResponse) GetServerResponse() *shared.ServerResponse {
	if o == nil {
		return nil
	}
	return o.ServerResponse
}

func (o *SendStringArrayResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SendStringArrayResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
