// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/blah/pkg/models/shared"
	"net/http"
)

type SendStringEnumArrayRequestBody struct {
	Days []shared.Days `form:"name=days"`
}

func (o *SendStringEnumArrayRequestBody) GetDays() []shared.Days {
	if o == nil {
		return []shared.Days{}
	}
	return o.Days
}

type SendStringEnumArrayRequest struct {
	RequestBody *SendStringEnumArrayRequestBody `request:"mediaType=application/x-www-form-urlencoded"`
	Array       bool                            `queryParam:"style=form,explode=true,name=array"`
}

func (o *SendStringEnumArrayRequest) GetRequestBody() *SendStringEnumArrayRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *SendStringEnumArrayRequest) GetArray() bool {
	if o == nil {
		return false
	}
	return o.Array
}

type SendStringEnumArrayResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// 500 Global
	GlobalTestException *shared.GlobalTestException
	ServerResponse      *shared.ServerResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *SendStringEnumArrayResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SendStringEnumArrayResponse) GetGlobalTestException() *shared.GlobalTestException {
	if o == nil {
		return nil
	}
	return o.GlobalTestException
}

func (o *SendStringEnumArrayResponse) GetServerResponse() *shared.ServerResponse {
	if o == nil {
		return nil
	}
	return o.ServerResponse
}

func (o *SendStringEnumArrayResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SendStringEnumArrayResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
