// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

// LocalTestException - To test specific local exceptions.
type LocalTestException struct {
	// Represents the specific endpoint info
	SecretMessageForEndpoint string `json:"SecretMessageForEndpoint"`
	// Represents the server's error code
	ServerCode int `json:"ServerCode"`
	// Represents the server's exception message
	ServerMessage string `json:"ServerMessage"`
}

var _ error = &LocalTestException{}

func (e *LocalTestException) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
