// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/speakeasy-sdks/blah/pkg/models/shared"
)

// NestedModelException - Precondition Failed
type NestedModelException struct {
	ServerCode    string          `json:"ServerCode"`
	ServerMessage string          `json:"ServerMessage"`
	Model         shared.Validate `json:"model"`
}

var _ error = &NestedModelException{}

func (e *NestedModelException) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
