// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

type Validate struct {
	Address *string `json:"address,omitempty"`
	Field   string  `json:"field"`
	Name    string  `json:"name"`
}

func (o *Validate) GetAddress() *string {
	if o == nil {
		return nil
	}
	return o.Address
}

func (o *Validate) GetField() string {
	if o == nil {
		return ""
	}
	return o.Field
}

func (o *Validate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
