// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GlobalTestException - To test specific global exceptions.
type GlobalTestException struct {
	// Represents the server's error code
	ServerCode int `json:"ServerCode"`
	// Represents the server's exception message
	ServerMessage string `json:"ServerMessage"`
}

func (o *GlobalTestException) GetServerCode() int {
	if o == nil {
		return 0
	}
	return o.ServerCode
}

func (o *GlobalTestException) GetServerMessage() string {
	if o == nil {
		return ""
	}
	return o.ServerMessage
}
