// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// LocalTestException - To test specific global exceptions.
type LocalTestException struct {
	// Represents the specific endpoint info
	SecretMessageForEndpoint string `json:"SecretMessageForEndpoint"`
	// Represents the server's error code
	ServerCode int `json:"ServerCode"`
	// Represents the server's exception message
	ServerMessage string `json:"ServerMessage"`
}

func (o *LocalTestException) GetSecretMessageForEndpoint() string {
	if o == nil {
		return ""
	}
	return o.SecretMessageForEndpoint
}

func (o *LocalTestException) GetServerCode() int {
	if o == nil {
		return 0
	}
	return o.ServerCode
}

func (o *LocalTestException) GetServerMessage() string {
	if o == nil {
		return ""
	}
	return o.ServerMessage
}
