// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// SuiteCode - A integer based enum representing a Suite in a game of cards
type SuiteCode int64

const (
	SuiteCodeOne   SuiteCode = 1
	SuiteCodeTwo   SuiteCode = 2
	SuiteCodeThree SuiteCode = 3
	SuiteCodeFour  SuiteCode = 4
)

func (e SuiteCode) ToPointer() *SuiteCode {
	return &e
}

func (e *SuiteCode) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 1:
		fallthrough
	case 2:
		fallthrough
	case 3:
		fallthrough
	case 4:
		*e = SuiteCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SuiteCode: %v", v)
	}
}
